import React from 'react';
import { Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { SprintPlan } from '../backend';

interface DownloadPdfButtonProps {
  plan: SprintPlan;
}

export default function DownloadPdfButton({ plan }: DownloadPdfButtonProps) {
  const handleDownload = () => {
    const printContent = buildPrintContent(plan);
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to download the PDF.');
      return;
    }

    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 500);
  };

  return (
    <Button
      onClick={handleDownload}
      variant="outline"
      className="border-blue-200 text-blue-700 hover:bg-blue-50 hover:border-blue-300 font-semibold rounded-xl gap-2"
    >
      <Download className="w-4 h-4" />
      Download PDF
    </Button>
  );
}

function buildPrintContent(plan: SprintPlan): string {
  const days = plan.days.map((day, i) => `
    <div class="day-card">
      <div class="day-header">Day ${i + 1}</div>
      <table>
        <tr><td class="label">Objective</td><td>${day.objectives}</td></tr>
        <tr><td class="label">Action Task</td><td>${day.actionTask}</td></tr>
        <tr><td class="label">Practice Exercise</td><td>${day.practiceExercise}</td></tr>
        <tr><td class="label">Deliverable</td><td>${day.deliverable}</td></tr>
        <tr><td class="label">Estimated Time</td><td>${Number(day.estimatedTime)} hour(s)</td></tr>
      </table>
    </div>
  `).join('');

  const mistakes = plan.commonMistakes.map((m) => `<li>${m}</li>`).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8" />
      <title>SkillSprint – ${plan.skillName} Plan</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a2e; padding: 32px; font-size: 13px; line-height: 1.6; }
        h1 { font-size: 24px; font-weight: 800; color: #1d4ed8; margin-bottom: 4px; }
        h2 { font-size: 16px; font-weight: 700; color: #1e3a8a; margin: 20px 0 8px; border-bottom: 2px solid #dbeafe; padding-bottom: 4px; }
        .subtitle { color: #6b7280; font-size: 13px; margin-bottom: 20px; }
        .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 20px; }
        .meta-item { background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 8px 12px; }
        .meta-item .key { font-size: 10px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; }
        .meta-item .val { font-weight: 600; color: #1e3a8a; font-size: 13px; }
        .overview { background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 8px; padding: 12px 16px; margin-bottom: 20px; }
        .day-card { border: 1px solid #e5e7eb; border-radius: 8px; margin-bottom: 12px; overflow: hidden; }
        .day-header { background: #1d4ed8; color: white; font-weight: 700; padding: 8px 14px; font-size: 13px; }
        table { width: 100%; border-collapse: collapse; }
        td { padding: 7px 14px; border-bottom: 1px solid #f3f4f6; vertical-align: top; }
        td.label { font-weight: 600; color: #374151; width: 140px; background: #f9fafb; font-size: 11px; text-transform: uppercase; letter-spacing: 0.03em; }
        .result-box { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 12px 16px; margin-bottom: 16px; }
        .mistakes-list { padding-left: 20px; }
        .mistakes-list li { margin-bottom: 4px; color: #dc2626; }
        .bonus { background: #fefce8; border: 1px solid #fde68a; border-radius: 8px; padding: 12px 16px; }
        .bonus a { color: #1d4ed8; }
        .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 11px; text-align: center; }
        @media print { body { padding: 16px; } }
      </style>
    </head>
    <body>
      <h1>SkillSprint – ${plan.skillName}</h1>
      <p class="subtitle">7-Day Skill Building Plan · Generated by SkillSprint</p>

      <div class="meta-grid">
        <div class="meta-item"><div class="key">Skill Level</div><div class="val">${plan.skillLevel}</div></div>
        <div class="meta-item"><div class="key">Hours / Day</div><div class="val">${Number(plan.hoursPerDay)} hrs</div></div>
        <div class="meta-item" style="grid-column: span 2"><div class="key">Desired Outcome</div><div class="val">${plan.desiredOutcome}</div></div>
      </div>

      <h2>Skill Overview</h2>
      <div class="overview">${plan.skillOverview}</div>

      <h2>7-Day Plan</h2>
      ${days}

      <h2>End of Week Result</h2>
      <div class="result-box">${plan.endOfWeekResult}</div>

      <h2>3 Common Mistakes to Avoid</h2>
      <ul class="mistakes-list">
        ${mistakes}
      </ul>

      <h2>Bonus Resource</h2>
      <div class="bonus">
        <strong>${plan.bonusResource.title}</strong><br/>
        <a href="${plan.bonusResource.url}" target="_blank">${plan.bonusResource.url}</a>
      </div>

      <div class="footer">Generated by SkillSprint · caffeine.ai</div>
    </body>
    </html>
  `;
}
