/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BonusResource = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
});
export const DayPlan = IDL.Record({
  'deliverable' : IDL.Text,
  'actionTask' : IDL.Text,
  'practiceExercise' : IDL.Text,
  'estimatedTime' : IDL.Nat,
  'objectives' : IDL.Text,
});
export const SprintPlan = IDL.Record({
  'endOfWeekResult' : IDL.Text,
  'unlockedStatus' : IDL.Bool,
  'bonusResource' : BonusResource,
  'planId' : IDL.Nat,
  'days' : IDL.Vec(DayPlan),
  'skillName' : IDL.Text,
  'commonMistakes' : IDL.Vec(IDL.Text),
  'hoursPerDay' : IDL.Nat,
  'skillLevel' : IDL.Text,
  'desiredOutcome' : IDL.Text,
  'skillOverview' : IDL.Text,
});
export const PublicPlanView = IDL.Record({
  'endOfWeekResult' : IDL.Text,
  'bonusResource' : BonusResource,
  'planId' : IDL.Nat,
  'skillName' : IDL.Text,
  'commonMistakes' : IDL.Vec(IDL.Text),
  'hoursPerDay' : IDL.Nat,
  'skillLevel' : IDL.Text,
  'desiredOutcome' : IDL.Text,
  'skillOverview' : IDL.Text,
  'firstDay' : DayPlan,
});

export const idlService = IDL.Service({
  'createPlan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getPlan' : IDL.Func([IDL.Nat], [IDL.Opt(SprintPlan)], ['query']),
  'getPublicPlanView' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PublicPlanView)],
      ['query'],
    ),
  'isPlanUnlocked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'submitTransactionId' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BonusResource = IDL.Record({ 'url' : IDL.Text, 'title' : IDL.Text });
  const DayPlan = IDL.Record({
    'deliverable' : IDL.Text,
    'actionTask' : IDL.Text,
    'practiceExercise' : IDL.Text,
    'estimatedTime' : IDL.Nat,
    'objectives' : IDL.Text,
  });
  const SprintPlan = IDL.Record({
    'endOfWeekResult' : IDL.Text,
    'unlockedStatus' : IDL.Bool,
    'bonusResource' : BonusResource,
    'planId' : IDL.Nat,
    'days' : IDL.Vec(DayPlan),
    'skillName' : IDL.Text,
    'commonMistakes' : IDL.Vec(IDL.Text),
    'hoursPerDay' : IDL.Nat,
    'skillLevel' : IDL.Text,
    'desiredOutcome' : IDL.Text,
    'skillOverview' : IDL.Text,
  });
  const PublicPlanView = IDL.Record({
    'endOfWeekResult' : IDL.Text,
    'bonusResource' : BonusResource,
    'planId' : IDL.Nat,
    'skillName' : IDL.Text,
    'commonMistakes' : IDL.Vec(IDL.Text),
    'hoursPerDay' : IDL.Nat,
    'skillLevel' : IDL.Text,
    'desiredOutcome' : IDL.Text,
    'skillOverview' : IDL.Text,
    'firstDay' : DayPlan,
  });
  
  return IDL.Service({
    'createPlan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getPlan' : IDL.Func([IDL.Nat], [IDL.Opt(SprintPlan)], ['query']),
    'getPublicPlanView' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PublicPlanView)],
        ['query'],
      ),
    'isPlanUnlocked' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'submitTransactionId' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };