/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BonusResource { 'url' : string, 'title' : string }
export interface DayPlan {
  'deliverable' : string,
  'actionTask' : string,
  'practiceExercise' : string,
  'estimatedTime' : bigint,
  'objectives' : string,
}
export interface PublicPlanView {
  'endOfWeekResult' : string,
  'bonusResource' : BonusResource,
  'planId' : bigint,
  'skillName' : string,
  'commonMistakes' : Array<string>,
  'hoursPerDay' : bigint,
  'skillLevel' : string,
  'desiredOutcome' : string,
  'skillOverview' : string,
  'firstDay' : DayPlan,
}
export interface SprintPlan {
  'endOfWeekResult' : string,
  'unlockedStatus' : boolean,
  'bonusResource' : BonusResource,
  'planId' : bigint,
  'days' : Array<DayPlan>,
  'skillName' : string,
  'commonMistakes' : Array<string>,
  'hoursPerDay' : bigint,
  'skillLevel' : string,
  'desiredOutcome' : string,
  'skillOverview' : string,
}
export interface _SERVICE {
  'createPlan' : ActorMethod<[string, bigint, string, string], bigint>,
  'getPlan' : ActorMethod<[bigint], [] | [SprintPlan]>,
  'getPublicPlanView' : ActorMethod<[bigint], [] | [PublicPlanView]>,
  'isPlanUnlocked' : ActorMethod<[bigint], boolean>,
  'submitTransactionId' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];